### ISSUE TITLE
unable to install helm/mern

### ISSUE THREAD

**Issue by rumanhassan** [IBM-Cloud/MERN-app#2]
I followed ReadMe doc and build the image mern-example:latest
then I executed helm install helm/mern. It throws following error:
Error: release vocal-chinchilla failed: Deployment in version "v1beta1" cannot be handled as a Deployment: v1beta1.Deployment: Spec: v1beta1.DeploymentSpec: Template: v1.PodTemplateSpec: Spec: v1.PodSpec: Containers: []v1.Container: v1.Container: Env: []v1.EnvVar: v1.EnvVar: Value: ReadString: expects " or n, parsing 423 ...,"value":3... at {"apiVersion":"extensions/v1beta1","kind":"Deployment","metadata":{"labels":{"chart":"mern-0.0.1"},"name":"mern-deployment","namespace":"default"},"spec":{"replicas":3,"revisionHistoryLimit":1,"template":{"metadata":{"labels":{"app":"mern-selector"}},"spec":{"containers":[{"env":[{"name":"MONGO_URL","value":"mongo"},{"name":"MONGO_DB_NAME","value":"test"},{"name":"NODE_ENV","value":"production"},{"name":"PORT","value":3000}],"image":"registry.ng.bluemix.net/robert_namespace/mern-example:v1","imagePullPolicy":"IfNotPresent","livenessProbe":{"httpGet":{"path":"/health","port":3000},"initialDelaySeconds":30,"periodSeconds":10},"name":"mern"}]}}}}

Can anyone please help me.

**Comment by joyychang** [comment]
Hi @rumanhassan 
Sorry for the late response.
Would you please try the latest update?

**Comment by jkingoliver** [comment]
@rumanhassan Please re-open this issue if it's not fixed in the latest version.
